wandb_version: 1

XN_activation:
  value: false
alpha_dim:
  value: vc
beta_dim:
  value: vc
data_norm:
  value: rw
dataset:
  value: Cora
epoch:
  value: 200
hidden_dim:
  value: 128
m2_mlp:
  value: true
method:
  value: euler
reaction_term:
  value: aggdiff-gat
self_loop_weight:
  value: 0
step_size:
  value: 0.25
time:
  value: 2.03
use_mlp:
  value: true
