wandb_version: 1

XN_activation:
  value: true
alpha_dim:
  value: sc
beta_dim:
  value: vc
data_norm:
  value: rw
dataset:
  value: Cora
epoch:
  value: 200
hidden_dim:
  value: 128
m2_mlp:
  value: false
method:
  value: euler
reaction_term:
  value: aggdiff-gat
self_loop_weight:
  value: 1
step_size:
  value: 0.45
time:
  value: 2.29
use_mlp:
  value: true
