wandb_version: 1

XN_activation:
  value: true
alpha_dim:
  value: sc
beta_dim:
  value: vc
data_norm:
  value: gcn
epoch:
  value: 200
hidden_dim:
  value: 32
m2_mlp:
  value: true
method:
  value: euler
self_loop_weight:
  value: 0
step_size:
  value: 0.25
time:
  value: 2.41
use_mlp:
  value: true
