wandb_version: 1

XN_activation:
  value: false
alpha_dim:
  value: vc
beta_dim:
  value: sc
data_norm:
  value: gcn
epoch:
  value: 200
hidden_dim:
  value: 256
m2_mlp:
  value: false
method:
  value: euler
self_loop_weight:
  value: 0
step_size:
  value: 0.4
time:
  value: 2.32
use_mlp:
  value: false
