wandb_version: 1

XN_activation:
  value: false
alpha_dim:
  value: vc
beta_dim:
  value: vc
data_norm:
  value: gcn
epoch:
  value: 200
hidden_dim:
  value: 32
m2_mlp:
  value: false
method:
  value: rk4
self_loop_weight:
  value: 1
step_size:
  value: 0.1
time:
  value: 2.29
use_mlp:
  value: true
