wandb_version: 1

XN_activation:
  value: true
alpha_dim:
  value: vc
beta_dim:
  value: sc
data_norm:
  value: gcn
epoch:
  value: 200
hidden_dim:
  value: 256
m2_mlp:
  value: false
method:
  value: rk4
self_loop_weight:
  value: 1
step_size:
  value: 0.30000000000000004
time:
  value: 2.36
use_mlp:
  value: false
