wandb_version: 1

XN_activation:
  value: true
alpha_dim:
  value: vc
beta_dim:
  value: vc
data_norm:
  value: gcn
epoch:
  value: 200
hidden_dim:
  value: 64
m2_mlp:
  value: false
method:
  value: rk4
reaction_term:
  value: cos_3
self_loop_weight:
  value: 1
step_size:
  value: 0.4
time:
  value: 2.18
use_mlp:
  value: false
