wandb_version: 1

XN_activation:
  value: true
alpha_dim:
  value: vc
beta_dim:
  value: sc
data_norm:
  value: rw
epoch:
  value: 200
hidden_dim:
  value: 256
m2_mlp:
  value: false
method:
  value: rk4
reaction_term:
  value: cos_1
self_loop_weight:
  value: 0
step_size:
  value: 0.4
time:
  value: 2.45
use_mlp:
  value: true
