wandb_version: 1

XN_activation:
  value: false
alpha_dim:
  value: sc
beta_dim:
  value: vc
data_norm:
  value: gcn
epoch:
  value: 200
hidden_dim:
  value: 128
m2_mlp:
  value: false
method:
  value: rk4
reaction_term:
  value: cos_1
self_loop_weight:
  value: 1
step_size:
  value: 0.30000000000000004
time:
  value: 2.33
use_mlp:
  value: false
