wandb_version: 1

XN_activation:
  value: false
alpha_dim:
  value: vc
beta_dim:
  value: sc
data_norm:
  value: rw
dataset:
  value: texas
epoch:
  value: 200
hidden_dim:
  value: 32
m2_mlp:
  value: true
method:
  value: rk4
reaction_term:
  value: aggdiff-log
self_loop_weight:
  value: 0
step_size:
  value: 0.5
time:
  value: 2.19
use_mlp:
  value: true
