wandb_version: 1

XN_activation:
  value: true
alpha_dim:
  value: sc
beta_dim:
  value: sc
data_norm:
  value: rw
dataset:
  value: texas
epoch:
  value: 200
hidden_dim:
  value: 128
m2_mlp:
  value: true
method:
  value: euler
reaction_term:
  value: aggdiff-log
self_loop_weight:
  value: 1
step_size:
  value: 0.1
time:
  value: 2.4
use_mlp:
  value: true
