name: gread
channels:
  - defaults
dependencies:
  - pip
  - python=3.9
  - pip:
    - deeprobust==0.2.4
    - ogb==1.3.3
    - torch==1.11.0+cu113
    - torch-geometric==2.0.4
    - torch-scatter==2.0.9
    - torch-sparse==0.6.14
    - torchdiffeq==0.2.3
    - wandb==0.12.21