wandb_version: 1

XN_activation:
  value: false
alpha_dim:
  value: vc
beta_dim:
  value: vc
data_norm:
  value: rw
dataset:
  value: texas
epoch:
  value: 200
hidden_dim:
  value: 128
m2_mlp:
  value: true
method:
  value: rk4
reaction_term:
  value: aggdiff-gat
self_loop_weight:
  value: 1
step_size:
  value: 0.45
time:
  value: 2.45
use_mlp:
  value: false
