wandb_version: 1

XN_activation:
  value: false
alpha_dim:
  value: sc
beta_dim:
  value: sc
data_norm:
  value: gcn
dataset:
  value: Cora
epoch:
  value: 200
hidden_dim:
  value: 256
m2_mlp:
  value: true
method:
  value: euler
self_loop_weight:
  value: 1
step_size:
  value: 0.1
time:
  value: 2.09
use_mlp:
  value: false
