wandb_version: 1

XN_activation:
  value: false
alpha_dim:
  value: sc
beta_dim:
  value: sc
data_norm:
  value: rw
dataset:
  value: Cora
epoch:
  value: 200
hidden_dim:
  value: 64
m2_mlp:
  value: true
method:
  value: rk4
self_loop_weight:
  value: 1
step_size:
  value: 0.35000000000000003
time:
  value: 2.35
use_mlp:
  value: true
