wandb_version: 1

XN_activation:
  value: false
alpha_dim:
  value: sc
beta_dim:
  value: vc
data_norm:
  value: rw
dataset:
  value: Cora
epoch:
  value: 200
hidden_dim:
  value: 128
m2_mlp:
  value: false
method:
  value: rk4
self_loop_weight:
  value: 1
step_size:
  value: 0.15000000000000002
time:
  value: 2.21
use_mlp:
  value: true
