wandb_version: 1

XN_activation:
  value: false
alpha_dim:
  value: sc
beta_dim:
  value: vc
data_norm:
  value: rw
dataset:
  value: Cora
epoch:
  value: 200
hidden_dim:
  value: 256
m2_mlp:
  value: true
method:
  value: euler
reaction_term:
  value: aggdiff-log
self_loop_weight:
  value: 1
step_size:
  value: 0.5
time:
  value: 2.03
use_mlp:
  value: true
