wandb_version: 1

XN_activation:
  value: false
alpha_dim:
  value: vc
beta_dim:
  value: vc
data_norm:
  value: rw
dataset:
  value: Cora
epoch:
  value: 200
hidden_dim:
  value: 256
m2_mlp:
  value: true
method:
  value: euler
reaction_term:
  value: aggdiff-log
self_loop_weight:
  value: 0
step_size:
  value: 0.45
time:
  value: 2.29
use_mlp:
  value: false
