wandb_version: 1

XN_activation:
  value: true
alpha_dim:
  value: vc
beta_dim:
  value: vc
data_norm:
  value: rw
dataset:
  value: Cora
epoch:
  value: 200
hidden_dim:
  value: 64
m2_mlp:
  value: true
method:
  value: euler
reaction_term:
  value: aggdiff-gauss
self_loop_weight:
  value: 1
step_size:
  value: 0.25
time:
  value: 2.08
use_mlp:
  value: true
