wandb_version: 1

XN_activation:
  value: false
alpha_dim:
  value: sc
beta_dim:
  value: sc
data_norm:
  value: gcn
dataset:
  value: Cora
epoch:
  value: 200
hidden_dim:
  value: 128
m2_mlp:
  value: true
method:
  value: rk4
reaction_term:
  value: aggdiff-gauss
self_loop_weight:
  value: 0
step_size:
  value: 0.35000000000000003
time:
  value: 2.21
use_mlp:
  value: false
