wandb_version: 1

XN_activation:
  value: false
alpha_dim:
  value: vc
beta_dim:
  value: sc
data_norm:
  value: rw
dataset:
  value: Cora
epoch:
  value: 200
hidden_dim:
  value: 256
m2_mlp:
  value: false
method:
  value: rk4
reaction_term:
  value: aggdiff-gauss
self_loop_weight:
  value: 1
step_size:
  value: 0.5
time:
  value: 2.29
use_mlp:
  value: true
