_wandb:
    value:
        cli_version: 0.17.7
        m:
            - "1": epoch_step
              "6":
                - 3
              "7": []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 77
            "2":
                - 1
                - 5
                - 53
                - 55
                - 77
            "3":
                - 2
                - 7
                - 16
                - 23
                - 55
            "4": 3.10.14
            "5": 0.17.7
            "8":
                - 5
            "12": 0.17.7
            "13": linux-x86_64
KNN_online:
    value: false
KNN_online_reps:
    value: 4
KNN_space:
    value: pos_distance
M_nodes:
    value: 64
XN_activation:
    value: true
add_source:
    value: false
adjoint:
    value: false
adjoint_method:
    value: adaptive_heun
adjoint_step_size:
    value: 1
allnumtrain:
    value: false
alltime:
    value: false
alpha:
    value: 1
alpha_dim:
    value: vc
att_samp_pct:
    value: 1
attention_dim:
    value: 64
attention_dropout:
    value: 0
attention_norm_idx:
    value: 0
attention_type:
    value: scaled_dot
augment:
    value: false
batch_norm:
    value: false
beltrami:
    value: false
beta_diag:
    value: true
beta_dim:
    value: vc
block:
    value: attention
data_norm:
    value: rw
dataset:
    value: film
decay:
    value: 0.0014341594128526826
device:
    value: cuda:4
diffusion_rate1:
    value: 0.8200000000000001
diffusion_rate2:
    value: 0.27
directional_penalty:
    value: null
dropout:
    value: 0.6450760407185196
earlystopxT:
    value: 3
edge_sampling:
    value: false
edge_sampling_T:
    value: T0
edge_sampling_add:
    value: 0.64
edge_sampling_add_type:
    value: importance
edge_sampling_epoch:
    value: 5
edge_sampling_online:
    value: false
edge_sampling_online_reps:
    value: 4
edge_sampling_rmv:
    value: 0.32
edge_sampling_space:
    value: attention
edge_sampling_sym:
    value: false
epoch:
    value: 200
exact:
    value: false
fa_layer:
    value: false
fc_out:
    value: false
feat_hidden_dim:
    value: 64
function:
    value: gread
gcn_bias:
    value: "False"
gcn_enc_dec:
    value: "False"
gcn_fixed:
    value: "False"
gcn_mid_dropout:
    value: "False"
gcn_non_lin:
    value: "False"
gcn_params:
    value: null
gcn_params_idx:
    value: 0
gcn_symm:
    value: "False"
gdc_avg_degree:
    value: 64
gdc_k:
    value: 64
gdc_method:
    value: ppr
gdc_sparsification:
    value: topk
gdc_threshold:
    value: 0.0001
geom_gcn_splits:
    value: true
gpu:
    value: 4
heads:
    value: 4
heat_time:
    value: 3
hetero_SL:
    value: false
hetero_undir:
    value: false
hidden_dim:
    value: 128
icxb:
    value: 1
input_dropout:
    value: 0.416670279482016
jacobian_norm2:
    value: null
kinetic_energy:
    value: null
label_rate:
    value: 0.5
leaky_relu_slope:
    value: 0.2
log_eps:
    value: 0.5
lr:
    value: 0.007850471605952366
m2_mlp:
    value: true
max_iters:
    value: 100
max_nfe:
    value: 5000
max_test_steps:
    value: 100
method:
    value: euler
mix_features:
    value: false
new_edges:
    value: random
no_alpha_sigmoid:
    value: false
no_early:
    value: true
noise:
    value: 0
noise_pos:
    value: null
not_lcc:
    value: true
nox0:
    value: false
num_splits:
    value: 1
num_train_per_class:
    value: 20
optimizer:
    value: adam
patience:
    value: null
planetoid_split:
    value: false
pos_enc_csv:
    value: false
pos_enc_hidden_dim:
    value: 32
pos_enc_orientation:
    value: row
pos_enc_type:
    value: GDC
ppr_alpha:
    value: 0.05
prediffuse:
    value: false
reaction_term:
    value: aggdiff-sin
reweight_attention:
    value: false
rewire_KNN:
    value: false
rewire_KNN_T:
    value: T0
rewire_KNN_epoch:
    value: 5
rewire_KNN_k:
    value: 64
rewire_KNN_sym:
    value: false
rewiring:
    value: null
run_track_reports:
    value: false
rw_addD:
    value: 0.02
rw_rmvR:
    value: 0.02
save_result:
    value: false
save_wandb_reports:
    value: false
self_loop_weight:
    value: 0
source_dim:
    value: sc
source_scale:
    value: 1
sparsify:
    value: S_hat
square_plus:
    value: false
step_size:
    value: 0.2
threshold_type:
    value: topk_adj
time:
    value: 0.17706405373935158
time_encoding:
    value: None
tol_scale:
    value: 1
tol_scale_adjoint:
    value: 1
total_deriv:
    value: null
trusted_mask:
    value: false
use_best_params:
    value: true
use_flux:
    value: false
use_labels:
    value: false
use_mlp:
    value: false
wandb:
    value: true
wandb_entity:
    value: username
wandb_project:
    value: grade-sweep
wandb_run_name:
    value: null
wandb_sweep:
    value: false
x0:
    value: false
