wandb_version: 1

XN_activation:
  value: false
alpha_dim:
  value: vc
beta_dim:
  value: vc
data_norm:
  value: gcn
dataset:
  value: texas
epoch:
  value: 200
hidden_dim:
  value: 64
m2_mlp:
  value: true
method:
  value: rk4
reaction_term:
  value: aggdiff-gauss
self_loop_weight:
  value: 0
step_size:
  value: 0.30000000000000004
time:
  value: 2.06
use_mlp:
  value: false
