wandb_version: 1

XN_activation:
  value: false
alpha_dim:
  value: vc
beta_dim:
  value: vc
data_norm:
  value: gcn
dataset:
  value: texas
epoch:
  value: 200
hidden_dim:
  value: 128
m2_mlp:
  value: true
method:
  value: euler
reaction_term:
  value: aggdiff-gauss
self_loop_weight:
  value: 1
step_size:
  value: 0.4
time:
  value: 2.15
use_mlp:
  value: false
